#!/bin/sh
#
#	  _  _____ 		
#	 | |/ / __|		https://gitlab.com/kauaG/
#	 | ' < (_ |		https://github.com/kauaG/
#	 |_|\_\___|		Follow me on Mastodon - @kauaG          	
#			
#	    
# terminal emulator
super + Return
	$TERMINAL

# program launcher
super + @space
    run_dmenu

# make sxhkd reload the configuration file
super + Escape
	pkill -USR1 -x sxhkd
  

