#!/bin/sh
#	  _  _____ 		
#	 | |/ / __|		https://gitlab.com/kauaG/
#	 | ' < (_ |		https://github.com/kauaG/
#	 |_|\_\___|		Follow me on Mastodon - @kauaG          	
#			
# A file to organize all my aliases

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

# Abbreviate commands.
alias \
	ka="killall" \
	g="git" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"
