#!/bin/sh
#	  _  _____ 		
#	 | |/ / __|		https://gitlab.com/kauaG/
#	 | ' < (_ |		https://github.com/kauaG/
#	 |_|\_\___|		Follow me on Mastodon - @kauaG          	
#			
# In ~/config/xprofile are some importants commands to run when start the graphical environment

. ~/.xprofile

# Start the WM 

ssh-agent dwm
